collections_config:
  data:
    path: _data
    schemas:
      doc:
        path: src/_schemas/data/doc.json
        create:
          path: '[relative_base_path]/{slug}.json'

collections_config_override: true

_inputs:
  sidebars:
    type: array
    options:
      structures: _structures.sidebarsGroup
  items:
    type: array
    options:
      structures: _structures.sidebarsItem
  items[*].url:
    type: select
    options:
      values: collections.all
      value_key: url

_structures:
  sidebarsGroup:
    values:
      - value:
          label:
          items:
  sidebarsItem:
    values:
      - value:
          label:
          url:
          items: