collections_config:
  topics:
    name: Topics
    path: 'content/en'
    schemas:
      default:
        path: src/_cloudcannon/schemas/topic.md
    _enabled_editors:
      - content
      - visual
    output: true
  data:
    path: _data
    schemas:
      doc:
        path: src/_schemas/data/doc.json
        create:
          path: '[relative_base_path]/{slug}.json'
      snippets:
        path: src/_cloudcannon/scehmas/snippets.json

collections_config_override: true

data_config:
  locale: true
  snippets: true

_editables:
  text:
    italic: true
  content:
    bold: true
    format: p h2 h3 h4 h5 h6
    italic: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    snippet: true

_inputs:
  trim_top_left:
    hidden: true
  trim_top_right:
    hidden: true
  trim_bottom_left:
    hidden: true
  trim_bottom_right:
    hidden: true
  sidebars:
    type: array
    options:
      structures: _structures.sidebarsGroup
  items:
    type: array
    options:
      structures: _structures.sidebarsItem

_structures:
  sidebarsGroup:
    values:
      - value:
          label:
          items:
  sidebarsItem:
    values:
      - value:
          label:
          url:
          items:

_snippets_imports:
  eleventy_liquid: true

_snippets:
  eleventy_snippet:
    template: eleventy_liquid_paired_shortcode_positional_args
    inline: true
    preview:
      text: Snippet
      subtext:
        - key: content
    definitions:
      shortcode_name: snippet2
      content_key: content
      positional_args:
        - editor_key: snippet_type
          type: string
          optional: true
    _inputs:
      content:
        type: markdown
      snippet_type:
        type: choice
        options:
          values: data.snippets
          value_key: key
          preview:
            text:
              - key: label
            image:
              - key: preview